name: Build and Release VS Code Extension

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'   # e.g., v0.1.0

permissions:
  contents: write  # needed for GitHub Release publishing

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Package .vsix
        run: npx vsce package
        # Output will be something like copy-folder-as-markdown-0.1.0.vsix

      - name: Upload .vsix artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: "*.vsix"
          if-no-files-found: error

  # Optional job: publish to the VS Code Marketplace on version tags
  publish:
    name: Publish to Marketplace
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # only on semver tags like v0.1.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --no-dependencies

      - name: Package .vsix
        run: vsce package

      - name: Create GitHub Release and upload .vsix
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
